### ISSUE TITLE
Remove no more existing bom io.syndesis:integration-runtime from dependency management

### ISSUE THREAD

**Issue by apupier** [lburgazzoli/syndesis-extension-example-xml#1]

**Comment by apupier** [comment]
@lburgazzoli it seems that it is now available again, or I'm mixing with another bom?? we removed it from the templates embedded in Fuse Tooling. What should we do?

**Comment by lburgazzoli** [comment]
what has been removed was `io.syndesis:syndesis-integration-bom` but `io.syndesis:syndesis-integration` has replaced it and it is required, hope we'll have a single bom in the future.

**Comment by apupier** [comment]
thanks for clarification
